# Generated by Django 3.2 on 2021-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=200)),
                ('movie', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, default=3, null=True)),
                ('upload_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='photoreview/')),
            ],
        ),
    ]
