# Generated by Django 3.2 on 2021-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='diary_body',
            new_name='review_body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='diary_title',
            new_name='review_title',
        ),
        migrations.AddField(
            model_name='blog',
            name='movie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
